### ISSUE TITLE
error: '::main' must return 'int'

### ISSUE THREAD

**Issue by genregasm** [MightyPork/avr-projects#2]
When I compiled in arduino...

sketch_feb12a:16: error: '::main' must return 'int'
sketch_feb12a:20: error: variable or field 'SECTION' declared void
sketch_feb12a:48: error: 'xrgb_t' does not name a type
sketch_feb12a:56: error: 'xrgb_t' does not name a type
sketch_feb12a.ino: In function 'void init_karts()':
sketch_feb12a:61: error: 'xrgb' was not declared in this scope
sketch_feb12a:61: error: expected primary-expression before ')' token
sketch_feb12a:61: error: expected `;' before '{' token
sketch_feb12a:62: error: expected primary-expression before ')' token
sketch_feb12a:62: error: expected `;' before '{' token
sketch_feb12a:63: error: expected primary-expression before ')' token
sketch_feb12a:63: error: expected `;' before '{' token
sketch_feb12a:64: error: expected primary-expression before ')' token
sketch_feb12a:64: error: expected `;' before '{' token
sketch_feb12a:65: error: expected primary-expression before ')' token
sketch_feb12a:65: error: expected `;' before '{' token
sketch_feb12a:66: error: expected primary-expression before ')' token
sketch_feb12a:66: error: expected `;' before '{' token
sketch_feb12a:67: error: expected primary-expression before ')' token
sketch_feb12a:67: error: expected `;' before '{' token
sketch_feb12a.ino: In function 'void move_karts()':
sketch_feb12a:78: error: 'inc_wrap' was not declared in this scope
sketch_feb12a:81: error: 'dec_wrap' was not declared in this scope
sketch_feb12a.ino: In function 'void render()':
sketch_feb12a:97: error: 'screen' was not declared in this scope
sketch_feb12a:97: error: 'xrgb' was not declared in this scope
sketch_feb12a:100: error: 'in_range_wrap' was not declared in this scope
sketch_feb12a:101: error: 'struct kart_t' has no member named 'color'
sketch_feb12a:101: error: 'add_xrgb' was not declared in this scope
sketch_feb12a:107: error: 'D6' was not declared in this scope
sketch_feb12a:107: error: 'screen' was not declared in this scope
sketch_feb12a:107: error: 'ws_send_xrgb' was not declared in this scope
sketch_feb12a.ino: At global scope:
sketch_feb12a:112: error: '::main' must return 'int'

**Comment by genregasm** [comment]
Ignore me, apparently I have no idea what I'm doing.

**Comment by MightyPork** [comment]
Sorry, it was midnight here when you asked. You have to compile it with *avr-gcc*, it's written in C, not the Arduino C++ hybrid.

Just run the makefile that comes with the project, and it will work (of course, you may need to adjust it for your arduino board).

**Comment by genregasm** [comment]
I couldn't get it to load into WinAVR.

**Comment by MightyPork** [comment]
Idk, you'll have to customize the makefile probably, I use Linux so can't really help you there. Honestly, I didn't know you can do stuff like this on Windows. What a strange idea...
